name: PR Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          chore
        requireScope: false
        
    - name: Check PR size
      run: |
        FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}..HEAD | wc -l)
        LINES_CHANGED=$(git diff --stat origin/${{ github.base_ref }}..HEAD | tail -1 | grep -o '[0-9]\+ insertions\|[0-9]\+ deletions' | grep -o '[0-9]\+' | awk '{sum+=$1} END {print sum}')
        
        if [ "$FILES_CHANGED" -gt 50 ]; then
          echo "⚠️ This PR changes $FILES_CHANGED files. Consider breaking it into smaller PRs."
        fi
        
        if [ "$LINES_CHANGED" -gt 1000 ]; then
          echo "⚠️ This PR has $LINES_CHANGED line changes. Consider breaking it into smaller PRs."
        fi
        
        echo "📊 PR Statistics:"
        echo "- Files changed: $FILES_CHANGED"
        echo "- Lines changed: $LINES_CHANGED"
        
    - name: Auto-assign reviewers
      uses: kentaro-m/auto-assign-action@v1.2.5
      with:
        configuration-path: '.github/auto-assign.yml'
        
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    needs: pr-validation
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'automerge')
      
    steps:
    - name: Auto-approve dependabot PRs
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Enable auto-merge
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
